### ISSUE TITLE
metadata on non-leaf nodes

### ISSUE THREAD

**Issue by BeckySharp** [WorldModelers/Ontologies#46]
... we should design a spec for this
@bgyori 
@chanys 
@MihaiSurdeanu 
@bnmin 
@kwalcock

**Comment by bgyori** [comment]
I just want to bump this issue since while working with the current wm_flat_metadata.yml, I realized that we currently wouldn't be able to detect that food_security and food_insecurity are opposites. This is because both of those are non-leaf nodes and therefore don't have their own set of properties.

**Comment by MihaiSurdeanu** [comment]
@bgyori : thanks for the reminder.
@BeckySharp and I will discuss it, and propose a draft representation here.

**Comment by bgyori** [comment]
I want to bump this issue again: I am seeing examples where users are curating statements and assigning grounding for certain texts to intermediate nodes in the ontology. However, these nodes currently don't have an "example" property and so it's not directly possible to extend the ontology YML with these texts as examples. What would be required to make this happen? I'm happy to help!
